export const UPDATE_GRID = 'UPDATE_GRID';
export const TOGGLE_GRID_NOTE = 'TOGGLE_GRID_NOTE';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const INCREASE_TEMPO = 'INCREASE_TEMPO';
export const DECREASE_TEMPO = 'DECREASE_TEMPO';
export const INCREASE_BARS = 'INCREASE_BARS';
export const DECREASE_BARS = 'DECREASE_BARS';

export const UPDATE_ACTIVE_STEP = 'UPDATE_ACTIVE_STEP';
